sudo: required
services: docker
language: generic

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo
    - my_url=https://github.com/cyber-dojo/start-points-languages.git
    - ./cyber-dojo start-point create languages --git=${my_url}
    - ./cyber-dojo start-point ls | grep languages
