sudo: required

services:
  - docker

script:
  - docker images

env:
    global:
        - DOCKER_ENGINE_VERSION=1.11.2

before_install:

    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

    # smoke test
    - docker run --rm hello-world

script:
    - docker version
    - docker images

    - MY_URL=https://github.com/cyber-dojo/default-languages.git

    - git clone --depth=1 --branch=master ${MY_URL} default-languages

    - docker volume create \
             --name=default-languages \
             --label=cyber-dojo-volume=${MY_URL}

    - cid=$(docker run --detach \
                       --interactive \
                       --net=none \
                       --user=root \
                       --volume=default-languages:/data \
                       cyberdojo/web:1.11.2 sh)

    - docker cp default-languages/. ${cid}:/data

    - docker exec ${cid} sh -c "cd /data && rm -rf .git"
    - docker exec ${cid} sh -c "chown -R cyber-dojo:cyber-dojo /data"
    - docker exec ${cid} sh -c "cd /usr/src/cyber-dojo/app/lib && ./check_setup_data.rb /data"
