sudo: required

services:
  - docker

script:
  - docker images

env:
    global:
        - DOCKER_ENGINE_VERSION=1.11.2

before_install:

    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

    # smoke test
    - docker run --rm hello-world

script:
    - docker version
    - docker images

    - echo "docker run --rm run cyberdojofoundation/web:${DOCKER_ENGINE_VERSION} sh -c 'cd ... && ./manifest-checker.rb https://github.com/cyber-dojo/default-languages.git'
 
