sudo: required
services: docker
language: node_js

script:
    - RAW=https://raw.githubusercontent.com/cyber-dojo
    - curl -O ${RAW}/commander/master/cyber-dojo
    - chmod +x cyber-dojo

    - LIST=${RAW}/start-points-languages/master/languages_list
    - ./cyber-dojo start-point create list_languages --list=${LIST}
    - ./cyber-dojo start-point ls | grep list_languages

    - npm install travis-ci
    - script=trigger-build.js
    - curl -O https://raw.githubusercontent.com/cyber-dojo/cyber-dojo/master/shared/${script}
    - node ${script} cyber-dojo/web
